ruoyi:
  name: IdealisticDaydreamer
  version: 1.0.0
  copyrightYear: 2020
  profile: /home/
  addressEnabled: true

server:
  port: 7500
  servlet:
    context-path: /
  tomcat:
    uri-encoding: UTF-8
    threads:
      max: 800
      min-spare: 30

logging:
  level:
    cn.az.wx: debug
    org.springframework: warn

spring:
  messages:
    basename: i18n/messages
  profiles:
    active: druid
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB
  devtools:
    restart:
      enabled: true
  redis:
    host: 180.76.169.35
    port: 6379
    password:
    timeout: 10s
    lettuce:
      pool:
        min-idle: 0
        max-idle: 8
        max-active: 8
        max-wait: -1ms

token:
  header: azusachino
  secret: azusakotorin
  # default 30min
  expireTime: 30

mybatis-plus:
  mapper-locations: classpath:mapper/**/*Mapper.xml
  type-handlers-package: cn.az.wx.framework.config.typehandler
  type-aliases-package: cn.az.wx.project.**.domain, cn.az.wx.project.**.entity
  global-config:
    banner: false
    db-config:
      id-type: auto

pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql

# 防止XSS攻击
xss:
  # 过滤开关
  enabled: true
  # 排除链接（多个用逗号分隔）
  excludes: /system/notice/*
  # 匹配链接
  urlPatterns: /system/*,/monitor/*,/tool/*

# 代码生成
gen:
  # 作者
  author: az
  # 默认生成包路径 system 需改成自己的模块名称 如 system monitor tool
  packageName: cn.az.wx.system
  # 自动去除表前缀，默认是true
  autoRemovePre: false
  # 表前缀（生成类名不会包含表前缀，多个用逗号分隔）
  tablePrefix: sys_

#微信账号配置
wx:
  mp:
    configs:
      - appId: 1111
        secret: 1111
        token: 111
        aesKey: 111
