server:
  port: 8088

spring:
  application:
    name: Little MIAOSHA
  datasource:
    druid:
      url: jdbc:mysql://127.0.0.1:3306/azusa?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
      username: root
      password: azusa520
      driver-class-name: com.mysql.cj.jdbc.Driver
      validation-query: SELECT 1

  redis:
    host: 127.0.0.1
    port: 6379
    password:
    jedis:
      pool:
        min-idle: 8
        max-idle: 500
        max-active: 2000
        max-wait: 10000
    timeout: 0

  aop:
    proxy-target-class: true

  messages:
    encoding: UTF-8

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false
    mode: HTML

mybatis:
  type-aliases-package: cn.az.project.miaosha.domain
  mapper-locations: classpath:/mapper/*.xml
  configuration:
    default-fetch-size: 100
    default-statement-timeout: 3000
    map-underscore-to-camel-case: true
