server:
  port: 8080

spring:
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/mysql
      username: root
      password: azusa520
      driver-class-name: com.mysql.cj.jdbc.Driver
      db-type: MYSQL
      validation-query: SELECT 1
