server:
  port: 8088

spring:
  application:
    name: Little MIAOSHA
  datasource:
    druid:
      url: jdbc:mysql://127.0.0.1:3306/azusa?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
      username: root
      password: azusa520
      driver-class-name: com.mysql.cj.jdbc.Driver
      filters: stat
      validation-query: SELECT 1
      max-active: 2
      initial-size: 1
      max-wait: 60000
      min-idle: 1
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      test-while-idle: false
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20

  redis:
    host: 127.0.0.1
    port: 6379
    password:
    jedis:
      pool:
        min-idle: 1
        max-idle: 10
        max-active: 10
        max-wait: 3
    timeout: 3

  aop:
    proxy-target-class: true

  messages:
    encoding: UTF-8

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false
    mode: HTML

mybatis:
  type-aliases-package: cn.az.project.miaosha.domain
  mapper-locations: classpath:/mapper/*.xml
  configuration:
    default-fetch-size: 100
    default-statement-timeout: 3000
    map-underscore-to-camel-case: true
