spring:
  application:
    name: csv-batch
  datasource:
    hikari:
      jdbc-url: jdbc:mysql://localhost:3306/test
      username: root
      password: azusa520
      driver-class-name: com.mysql.cj.jdbc.Driver
      connection-test-query: SELECT 1
  batch:
    initialize-schema: always
