server:
  port: 8080

spring:
  main:
    allow-bean-definition-overriding: true # druid的DataSource和Sharding的DataSource
  application:
    name: little-sharding

sharding:
  jdbc:
    datasource:
      names: my-master,my-slave,pg-master,pg-slave # 不能含有空格
      my-master:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://180.76.169.35:3306/demo?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false
        username: root
        password: azusa520
        filters: stat
        validation-query: SELECT 1
        max-active: 2
        initial-size: 1
        max-wait: 60000
        min-idle: 1
        time-between-eviction-runs-millis: 60000
        min-evictable-idle-time-millis: 300000
        test-while-idle: false
        test-on-borrow: false
        test-on-return: false
        pool-prepared-statements: true
        max-pool-prepared-statement-per-connection-size: 20
      my-slave:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://180.76.169.35:3306/demo?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false
        username: root
        password: azusa520
        filters: stat
        validation-query: SELECT 1
        max-active: 2
        initial-size: 1
        max-wait: 60000
        min-idle: 1
        time-between-eviction-runs-millis: 60000
        min-evictable-idle-time-millis: 300000
        test-while-idle: false
        test-on-borrow: false
        test-on-return: false
        pool-prepared-statements: true
        max-pool-prepared-statement-per-connection-size: 20
      pg-master:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: org.postgresql.Driver
        url: jdbc:postgresql://180.76.169.35:5432/azusa
        username: postgres
        password: azusa520
        filters: stat
        validation-query: SELECT 1
        max-active: 2
        initial-size: 1
        max-wait: 60000
        min-idle: 1
        time-between-eviction-runs-millis: 60000
        min-evictable-idle-time-millis: 300000
        test-while-idle: false
        test-on-borrow: false
        test-on-return: false
        pool-prepared-statements: true
        max-pool-prepared-statement-per-connection-size: 20
      pg-slave:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: org.postgresql.Driver
        url: jdbc:postgresql://180.76.169.35:5432/azusa
        username: postgres
        password: azusa520
        filters: stat
        validation-query: SELECT 1
        max-active: 2
        initial-size: 1
        max-wait: 60000
        min-idle: 1
        time-between-eviction-runs-millis: 60000
        min-evictable-idle-time-millis: 300000
        test-while-idle: false
        test-on-borrow: false
        test-on-return: false
        pool-prepared-statements: true
        max-pool-prepared-statement-per-connection-size: 20
    config:
      props:
        sql:
          show: true
      sharding:
        master-slave-rules:
          first:
            masterDataSourceName: my-master
            slaveDataSourceNames:
              - my-slave
            loadBalanceAlgorithmType: ROUND_ROBIN
          second:
            masterDataSourceName: pg-master
            slaveDataSourceNames:
              - pg-slave
            loadBalanceAlgorithmType: ROUND_ROBIN
        default-data-source-name: first
        default-database-strategy:
          hint:
            algorithm-class-name: cn.az.project.alg.MyDataSourceRoutingAlgorithm

mybatis-plus:
  global-config:
    banner: off
    db-config:
      id-type: auto
  configuration:
    default-enum-type-handler: com.baomidou.mybatisplus.extension.handlers.MybatisEnumTypeHandler
    jdbc-type-for-null: varchar
  type-aliases-package: cn.az.project.entity
  mapper-locations: classpath*:/mapper/**/*.xml
